name: Update App Version on Deploy

on:
  push:
    branches:
      - main  # Change to your production branch

jobs:
  update-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Extract version from package.json
        id: package-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Update Supabase app_versions table
        env:
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          RESPONSE=$(curl --location -X POST "https://suisrrsmangoaadjoovj.supabase.co/functions/v1/update-app-version" \
            -H "Authorization: Bearer $SUPABASE_ANON_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"version\": \"${{ steps.package-version.outputs.version }}\"}" \
            -w "\nHTTP_STATUS:%{http_code}" \
            -s)

          echo "$RESPONSE"

          HTTP_STATUS=$(echo "$RESPONSE" | grep -o "HTTP_STATUS:[0-9]*" | cut -d: -f2)

          if [ "$HTTP_STATUS" != "200" ]; then
            echo "❌ Failed to update version. HTTP Status: $HTTP_STATUS"
            exit 1
          fi

          echo "✅ Successfully updated version to ${{ steps.package-version.outputs.version }}"

